# Fill in your AWS Access Key ID and Secret Access Key
# http://aws.amazon.com/security-credentials
defaults: &defaults
  access_key_id: <%= ENV['PRIZZM_S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['PRIZZM_S3_SECRET_ACCESS_KEY'] %>

development:
  <<: *defaults
  simple_db_consistent_reads: false

production:
  <<: *defaults
  simple_db_consistent_reads: true
