development:
  #host: localhost
  #database: prizzm_development
  uri: <%= ENV['MONGOLAB_URI'] %>

test:
  host: localhost
  database: prizzm_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
