require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrizzmInvitationsController do

  # This should return the minimal set of attributes required to create a valid
  # PrizzmInvitation. As you add validations to PrizzmInvitation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all prizzm_invitations as @prizzm_invitations" do
      prizzm_invitation = PrizzmInvitation.create! valid_attributes
      get :index
      assigns(:prizzm_invitations).should eq([prizzm_invitation])
    end
  end

  describe "GET show" do
    it "assigns the requested prizzm_invitation as @prizzm_invitation" do
      prizzm_invitation = PrizzmInvitation.create! valid_attributes
      get :show, :id => prizzm_invitation.id.to_s
      assigns(:prizzm_invitation).should eq(prizzm_invitation)
    end
  end

  describe "GET new" do
    it "assigns a new prizzm_invitation as @prizzm_invitation" do
      get :new
      assigns(:prizzm_invitation).should be_a_new(PrizzmInvitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested prizzm_invitation as @prizzm_invitation" do
      prizzm_invitation = PrizzmInvitation.create! valid_attributes
      get :edit, :id => prizzm_invitation.id.to_s
      assigns(:prizzm_invitation).should eq(prizzm_invitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrizzmInvitation" do
        expect {
          post :create, :prizzm_invitation => valid_attributes
        }.to change(PrizzmInvitation, :count).by(1)
      end

      it "assigns a newly created prizzm_invitation as @prizzm_invitation" do
        post :create, :prizzm_invitation => valid_attributes
        assigns(:prizzm_invitation).should be_a(PrizzmInvitation)
        assigns(:prizzm_invitation).should be_persisted
      end

      it "redirects to the created prizzm_invitation" do
        post :create, :prizzm_invitation => valid_attributes
        response.should redirect_to(PrizzmInvitation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prizzm_invitation as @prizzm_invitation" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrizzmInvitation.any_instance.stub(:save).and_return(false)
        post :create, :prizzm_invitation => {}
        assigns(:prizzm_invitation).should be_a_new(PrizzmInvitation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrizzmInvitation.any_instance.stub(:save).and_return(false)
        post :create, :prizzm_invitation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prizzm_invitation" do
        prizzm_invitation = PrizzmInvitation.create! valid_attributes
        # Assuming there are no other prizzm_invitations in the database, this
        # specifies that the PrizzmInvitation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PrizzmInvitation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => prizzm_invitation.id, :prizzm_invitation => {'these' => 'params'}
      end

      it "assigns the requested prizzm_invitation as @prizzm_invitation" do
        prizzm_invitation = PrizzmInvitation.create! valid_attributes
        put :update, :id => prizzm_invitation.id, :prizzm_invitation => valid_attributes
        assigns(:prizzm_invitation).should eq(prizzm_invitation)
      end

      it "redirects to the prizzm_invitation" do
        prizzm_invitation = PrizzmInvitation.create! valid_attributes
        put :update, :id => prizzm_invitation.id, :prizzm_invitation => valid_attributes
        response.should redirect_to(prizzm_invitation)
      end
    end

    describe "with invalid params" do
      it "assigns the prizzm_invitation as @prizzm_invitation" do
        prizzm_invitation = PrizzmInvitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrizzmInvitation.any_instance.stub(:save).and_return(false)
        put :update, :id => prizzm_invitation.id.to_s, :prizzm_invitation => {}
        assigns(:prizzm_invitation).should eq(prizzm_invitation)
      end

      it "re-renders the 'edit' template" do
        prizzm_invitation = PrizzmInvitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrizzmInvitation.any_instance.stub(:save).and_return(false)
        put :update, :id => prizzm_invitation.id.to_s, :prizzm_invitation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prizzm_invitation" do
      prizzm_invitation = PrizzmInvitation.create! valid_attributes
      expect {
        delete :destroy, :id => prizzm_invitation.id.to_s
      }.to change(PrizzmInvitation, :count).by(-1)
    end

    it "redirects to the prizzm_invitations list" do
      prizzm_invitation = PrizzmInvitation.create! valid_attributes
      delete :destroy, :id => prizzm_invitation.id.to_s
      response.should redirect_to(prizzm_invitations_url)
    end
  end

end
